import SimpleSchema from 'simpl-schema';

import Events from '/imports/api/events';
import { EventId, EventTheme } from './event';

const AUTOTEXT_TRIGGERS_BASE = [
  'WELCOME',
  'WELCOME_NO_IMAGE',
  'WELCOME_NO_FACE',
  'WELCOME_MULTI_FACES',

  'TENTATIVE_NO_IMAGE',
  'TENTATIVE_NO_FACE',
  'TENTATIVE_MULTI_FACES',
  'TENTATIVE_WELCOME',

  'CHECKPOINT_FOUND',
  'CHECKPOINT_FOUND_HIDDEN',
  'CHECKPOINT_ALREADY_FOUND',
  'CHECKPOINT_ALREADY_FOUND_HIDDEN',

  'SIGN_OFF',
  'SIGN_BACK_ON',

  'INVALID_COMMAND',
  'INVALID_HASHTAG',
  'INVALID_BET',
  'INVALID_REGULAR_TEXT',
  'INVALID_MEDIA_ONLY_TEXT',
  'HELP',

  'SENT_VIDEO',
  'INVALID_CONTENT_TYPE',

  'MISSION_PRESTART',
  'MISSION_START_PLAYER_A',
  'MISSION_START_PLAYER_B',
  'MISSION_COMPLETE',
  'MISSION_FAIL',
  'MISSION_ALREADY_COMPLETED',

  'ALIAS_CHANGED',
  'ALIAS_MISSION_ACTIVE',

  'ACHIEVEMENT_UNLOCK',
  'ACHIEVEMENT_UNLOCK_DURING_REVEAL',
  'ALL_ACHIEVEMENTS_UNLOCKED',
] as const;
type AutoTextBaseTrigger = (typeof AUTOTEXT_TRIGGERS_BASE)[number];

const AUTOTEXT_TRIGGERS_CASINO = [
  'WALLET_STATUS',

  'WALLET_MORETHAN_N',
  'WALLET_LESSTHAN_N',
  'WALLET_BANKRUPT',

  'SLOT_SPIN',
  'SLOT_WIN_SMALL',
  'SLOT_WIN_MEDIUM',
  'SLOT_WIN_BIG',
  'SLOT_WIN_HACKER',
  'SLOT_WIN_HACKER_PARTIAL',
  'SLOT_LOSE',
  'SLOT_BUSY',
  'SLOT_NOT_ENOUGH_MONEY',
  'SLOT_NO_MONEY',
  // 'SLOT_QUEUE',
  'SLOT_UNAVAILABLE',

  'ROULETTE_BET',
  'ROULETTE_LOSE',
  'ROULETTE_WIN_SMALL',
  'ROULETTE_WIN_NUMBER',
  'ROULETTE_NOT_YET_ACCEPTING',
  'ROULETTE_BET_TOO_LATE',
  'ROULETTE_NOT_ENOUGH_MONEY',
  'ROULETTE_NO_MORE',
  'ROULETTE_BET_ZERO',

  'QUESTS_NO_TASKS_LEFT',
  'QUESTS_NO_SLOTS_LEFT',

  'HACKER_ROULETTE_SIMPLE',
  'HACKER_ROULETTE_MATH',
] as const;
type AutoTextCasinoTrigger = (typeof AUTOTEXT_TRIGGERS_CASINO)[number];

const AUTOTEXT_TRIGGERS_CLUE = [
  'CLUE_REWARD_PRE',

  'CLUE_REWARD_POST_ROOM',
  'CLUE_REWARD_POST_COMPLETE_ROOM',
  'CLUE_REWARD_POST_PERSON',
  'CLUE_REWARD_POST_COMPLETE_PERSON',
  'CLUE_REWARD_POST_WEAPON',
  'CLUE_REWARD_POST_COMPLETE_WEAPON',

  'CLUE_REWARD_NONE_LEFT_ROOM',
  'CLUE_REWARD_NONE_LEFT_PERSON',
  'CLUE_REWARD_NONE_LEFT_WEAPON',
  'CLUE_REWARD_NONE_LEFT_ANY',

  'GUESS_PERSON_SUCCESS',
  'GUESS_PERSON_INVALID',
  'GUESS_PERSON_EMPTY',

  'GUESS_ROOM_SUCCESS',
  'GUESS_ROOM_INVALID',
  'GUESS_ROOM_EMPTY',

  'GUESS_WEAPON_SUCCESS',
  'GUESS_WEAPON_INVALID',
  'GUESS_WEAPON_EMPTY',

  'GUESS_N_REMAINING',

  'ROUND_BEGIN',
  'ROUND_COUNTDOWN',
  'ROUND_REVEAL_START',
  'ROUND_REVEAL_RESULT_N_CLUES',
  'ROUND_END',
] as const;
type AutoTextClueTrigger = (typeof AUTOTEXT_TRIGGERS_CLUE)[number];

const AUTOTEXT_TRIGGERS_DERBY = [
  'TELLER_REJECT_NO_RACES',
  'TELLER_REJECT_RACE_ACTIVE',
  'TELLER_REJECT_BETTING_NOT_YET_OPEN',
  'TELLER_REJECT_NOT_EXIST',
  'TELLER_REJECT_NOT_HERE_NOW',
  'TELLER_REJECT_BUSY_WITH_OTHER_PLAYER',
  'TELLER_REJECT_OTHER_BET_IN_PROGRESS',
  'TELLER_REJECT_NOT_ENOUGH_MONEY',

  'TELLER_BET_TYPE',
  'TELLER_BET_HORSE_WIN',
  'TELLER_BET_HORSE1_TRIFECTA',
  'TELLER_BET_HORSE2_TRIFECTA',
  'TELLER_BET_HORSE3_TRIFECTA',
  'TELLER_BET_WAGER',
  'TELLER_BET_WAGER_TRIFECTA',
  'TELLER_BET_PLACED_WIN',
  'TELLER_BET_PLACED_TRIFECTA',

  'TELLER_ERROR_ALREADY_ANSWERED_STEP',
  'TELLER_ERROR_ALREADY_PLACED_BET',
  'TELLER_ERROR_ALREADY_CANCELLED_BET',

  'TELLER_CANCEL_USER',
  'TELLER_CANCEL_TIMEOUT',
  'TELLER_CANCEL_RACE',

  'HORSE_POWERUP_SPEED',
  'HORSE_POWERUP_ENDURANCE',
  'HORSE_POWERUP_WATER_RESISTANCE',
  'HORSE_POWERUP_WIND_RESISTANCE',
  'HORSE_POWERUP_ELECTRIC_RESISTANCE',

  'FORTUNE_TELLER_ADVICE_TYPE',
  'FORTUNE_TELLER_HORSE_RANKING',
  'FORTUNE_TELLER_STAT_SPEED_TOP',
  'FORTUNE_TELLER_STAT_SPEED_BOTTOM',
  'FORTUNE_TELLER_STAT_ENDURANCE_TOP',
  'FORTUNE_TELLER_STAT_ENDURANCE_BOTTOM',
  'FORTUNE_TELLER_STAT_WATER_RESISTANCE_TOP',
  'FORTUNE_TELLER_STAT_WATER_RESISTANCE_BOTTOM',
  'FORTUNE_TELLER_STAT_WIND_RESISTANCE_TOP',
  'FORTUNE_TELLER_STAT_WIND_RESISTANCE_BOTTOM',
  'FORTUNE_TELLER_STAT_ELECTRIC_RESISTANCE_TOP',
  'FORTUNE_TELLER_STAT_ELECTRIC_RESISTANCE_BOTTOM',

  'FORTUNE_TELLER_TIMEOUT',
  'FORTUNE_TELLER_ERROR_ALREADY_TIMEDOUT',
  'FORTUNE_TELLER_ERROR_ALREADY_GIVEN',

  'FORTUNE_TELLER_NOT_HERE_NOW',
  'FORTUNE_TELLER_BUSY_WITH_OTHER_PLAYER',
  'FORTUNE_TELLER_NOT_ENOUGH_MONEY',

  'RACEBET_RESULT_WIN_BIG',
  'RACEBET_RESULT_WIN',
  'RACEBET_RESULT_TRIFECTA',
  'RACEBET_RESULT_LOSE',
] as const;
type AutoTextDerbyTrigger = (typeof AUTOTEXT_TRIGGERS_DERBY)[number];

const AUTOTEXT_TRIGGERS = [
  ...AUTOTEXT_TRIGGERS_BASE,
  ...AUTOTEXT_TRIGGERS_CASINO,
  ...AUTOTEXT_TRIGGERS_CLUE,
  ...AUTOTEXT_TRIGGERS_DERBY,
] as const;
type AutoTextTrigger = (typeof AUTOTEXT_TRIGGERS)[number];

const THEME_TRIGGERS: Record<EventTheme, AutoTextTrigger[]> = {
  casino: [...AUTOTEXT_TRIGGERS_CASINO],
  clue: [...AUTOTEXT_TRIGGERS_CLUE],
  derby: [...AUTOTEXT_TRIGGERS_DERBY],
};

const AutoTextSchema = new SimpleSchema({
  event: {
    type: String,
    allowedValues: Events.allIds,
  },
  playerText: String,
  trigger: {
    type: String,
    allowedValues: [...AUTOTEXT_TRIGGERS],
  },
  triggerNum: {
    type: SimpleSchema.Integer,
    optional: true,
  },
  image_url: {
    type: String,
    optional: true,
  },
});

export type AutoTextId = string;

interface AutoText {
  _id: AutoTextId;
  event: EventId;
  playerText: string;
  trigger: string;
  triggerNum: number;
  image_url?: string;
}

export default AutoTextSchema;
export { AutoTextSchema };
export type {
  AutoText,
  AutoTextTrigger,
  AutoTextBaseTrigger,
  AutoTextCasinoTrigger,
  AutoTextClueTrigger,
  AutoTextDerbyTrigger,
};
export { AUTOTEXT_TRIGGERS, THEME_TRIGGERS, AUTOTEXT_TRIGGERS_BASE };
